### PR TITLE
Structured degrees iteration

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
* Show undergraduate degree grades for postgraduate degree types
* Allow Level 7 degree types to be selected for first degree (i.e. bachelors and masters, but not doctorates)
* Allow other degree types to be entered
* Improve autosuggest UX

### CODE REVIEW

**Comment by fofr** [comment]
I wonder if we need to do better with fuzzy matching?

Screen Shot 2020-04-23 at 08 57 55

**Comment by fofr** [comment]
In other places, "Other" gives a free text field, which is what I expected.

Screen Shot 2020-04-23 at 09 00 50

**Comment by EmmaFrith** [comment]
> I wonder if we need to do better with fuzzy matching?
> 
> (I think I prefer "Which institution did you study at?", rather than "go to", to cover online degrees)
> 
> Screen Shot 2020-04-23 at 08 57 55

Good point @fofr - I'm happy with that

**Comment by EmmaFrith** [comment]
> In other places, "Other" gives a free text field, which is what I expected.
> 
> Screen Shot 2020-04-23 at 09 00 50

I was also expecting other to be free text

**Pull request merged**
