### PR TITLE
Apply 2 updates

### PR DESCRIPTION
**Pull request by adamsilver**
@paulrobertlloyd this PR is increasing in size and taken me a fair amount of work so will do rest of the ticket in separate PR.

Application page:
image

Individual tasks now have checkboxes:
image

Review page now reflects those state for each task:
image

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
Functionally, this seems to work great! Labelling wise, not so sure. But feel to create a new PR for that.

**Comment by paulrobertlloyd** [comment]
Actually, ‘Not started’ is not shown when creating a new Apply 1 application (small thing right now, but worth pointing out)

**Comment by fofr** [comment]
Why was Previous applications moved below Need help?

**Comment by paulrobertlloyd** [comment]
> Why was Previous applications moved below Need help?

Because there’s no evidence of candidates wanting to see previous applications, but they are more likely to want help.

**Pull request merged**
